"""
open_upgrade_pr.py
Reads every proposal in upgrade_proposals/ and opens (or updates) a
GitHub pull request against each target system's default branch,
describing the tier upgrade. Requires GITHUB_TOKEN env var.
"""

import json
import os
import glob
from datetime import datetime, timezone

try:
    from github import Github
except ImportError:
    Github = None

PROPOSALS_DIR = "upgrade_proposals"
OWNER = "Garrettc123"


def main():
    token = os.environ.get("GITHUB_TOKEN")
    if not token or Github is None:
        print("GITHUB_TOKEN not set or PyGithub unavailable — skipping live PR creation (dry run).")
        for path in glob.glob(f"{PROPOSALS_DIR}/*.json"):
            with open(path) as f:
                p = json.load(f)
            print(f"[DRY RUN] Would open PR on {p['system']}: {p['from_tier']} -> {p['to_tier']}")
        return

    gh = Github(token)
    for path in glob.glob(f"{PROPOSALS_DIR}/*.json"):
        with open(path) as f:
            proposal = json.load(f)

        repo_name = proposal["system"]
        try:
            repo = gh.get_repo(f"{OWNER}/{repo_name}")
        except Exception as e:
            print(f"Skipping {repo_name}: {e}")
            continue

        branch_name = f"upgrade/tier-{proposal['to_tier']}-{datetime.now(timezone.utc).strftime('%Y%m%d')}"
        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha

        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        except Exception:
            pass  # branch may already exist

        title = f"Upgrade: {proposal['from_tier']} -> {proposal['to_tier']}"
        body = (
            f"{proposal['description']}\n\n"
            f"Files targeted: {', '.join(proposal['files_to_add_or_modify'])}\n\n"
            f"Generated by nightly-upgrade-loop at {proposal['generated_at']}"
        )

        existing = [pr for pr in repo.get_pulls(state="open") if pr.head.ref == branch_name]
        if existing:
            print(f"PR already open for {repo_name}: {existing[0].html_url}")
            continue

        try:
            pr = repo.create_pull(title=title, body=body, head=branch_name, base=default_branch)
            print(f"Opened PR: {pr.html_url}")
        except Exception as e:
            print(f"Could not open PR for {repo_name}: {e}")


if __name__ == "__main__":
    main()
